background = #29292c
foreground = #c3c3c4
cursor-color = #c3c3c4
cursor-text = #29292c
selection-background = #4a4a4e
selection-foreground = #c3c3c4

palette = 0=#3a3a3e
palette = 1=#b8626a
palette = 2=#b98d7b
palette = 3=#c4b28a
palette = 4=#87a987
palette = 5=#8ba4b0
palette = 6=#938aa9
palette = 7=#c3c3c4

palette = 8=#777b74
palette = 9=#d4737c
palette = 10=#d4a892
palette = 11=#deca9f
palette = 12=#9dc09d
palette = 13=#a2bcc9
palette = 14=#ada5c3
palette = 15=#e7ecf4
