set -g default-terminal "screen-256color"
set -as terminal-overrides ",*:Tc"

set -g mouse on
set -g mode-keys vi

unbind C-b
set -g prefix C-a
bind C-Space send-prefix

set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g base-index 1

accent="#8caaee"
white="#c6d0f5"
dim="#a5adce"
highlight="#414559"

set -g pane-border-style "fg=$highlight"
set -g pane-active-border-style "fg=$accent"
set -g mode-style "bg=$highlight,fg=$white"
set -g message-style "bg=$highlight,fg=$white"
set -g clock-mode-colour "$accent"

set -g status-position top
set -g status-style "bg=default"
set -g status-left-length 50
set -g status 2
set -g status-interval 1
set -g status-format[1] ""
set -g status-left "#[fg=$accent,bg=default]  #[fg=$white,bg=default] #S "
set -g window-status-format "#[fg=$white,bg=default] #I #W "
set -g window-status-current-format "#[fg=$white,bg=$highlight] #I #W "
set -g status-right " #[fg=$accent,bg=default]%H:%M "
